---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
webhooks:
  - name: armo-validation.default.svc
    clientConfig:
      service:
        name: admission-server-armo
        namespace: default
        path: "/armo-admission-controler"
      caBundle: "${CA_BUNDLE}"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["pods", "deployments"]
    failurePolicy: Ignore
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation
webhooks:
  - name: armo-mutation.default.svc
    clientConfig:
      service:
        name: admission-server-armo
        namespace: default
        path: "/armo-admission-controler"
      caBundle: "${CA_BUNDLE}"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["pods", "deployments"]
    failurePolicy: Ignore