---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
webhooks:
  - name: armo-validation.default.svc
    clientConfig:
      service:
        name: admission-server-armo
        namespace: default
        path: "/armo-admission-controller/validating"
      caBundle: "${CA_BUNDLE}"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "deployments", "pods/exec"]
    failurePolicy: Ignore
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation
webhooks:
  - name: armo-mutation.default.svc
    clientConfig:
      service:
        name: admission-server-armo
        namespace: default
        path: "/armo-admission-controller/mutating"
      caBundle: "${CA_BUNDLE}"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "deployments", "pods/exec"]
    failurePolicy: Ignore